spring:
  application:
    name: countries-be
  profiles:
    active: dev
#eger port degıstırmek ısteseydık server:
# port:8181  seklınde kullanabılırdık.
server:
  port: 8181
  servlet:
    context-path: /api  #erısmek ısteyenler api uzantısını vermesı gerekıyor bu sayede bız api java da ve country controller da belırtmeme gerek yok.
